### PR TITLE
Stop scanning if wpa_supplicant state goes INACTIVE.

### LINKED ISSUE #12: Scan taking a full 20 seconds on Kobo Aura
I was emboldened to try and figure out why my Kobo Aura always shows "Scanning for networks..." for a full 20 seconds each time it connects to Wi-Fi...

Uncommenting the print statements in `wpaclient.lua` (and adding two of my own log lines in koreader to confirm timing), I see:

```
10/10/24-21:38:37 DEBUG WpaSupplicant:getNetworkList scanning 
SCAN reply:     OK
3       1       1       0       CTRL-EVENT-BSS-ADDED 0 14:d8:64:xx:xx:xx
4       1       1       0       CTRL-EVENT-BSS-ADDED 1 d4:6e:0e:xx:xx:xx
5       1       1       1       CTRL-EVENT-SCAN-RESULTS
5       2       1       1       CTRL-EVENT-NETWORK-NOT-FOUND
10/10/24-21:38:57 DEBUG WpaSupplicant:getNetworkList scan done 
```

It seems like in the case of the Aura, this comment is wrong:

```
            -- If we get CTRL-EVENT-NETWORK-NOT-FOUND, it means no preferred networks were found during the scan.
            -- It also means *another* scan will be fired, so this invalidates CTRL-EVENT-SCAN-RESULTS,
            -- as the actual CTRL-EVENT-SCAN-STARTED may be delayed until our next iteration...
            -- It may take *multiple* scans, and events may be split across multiple reads...
            -- Which is why NetworkManager does another pass of waiting in case our heuristics fail...
            elseif ev.msg == "CTRL-EVENT-NETWORK-NOT-FOUND" then
                found_result = false
                expected_scans = expected_scans + 1
```

On the Aura, seems wpa_supplicant sends `CTRL-EVENT-NETWORK-NOT-FOUND` but doesn't start any new scan.

I note that the Aura is also one of the "older devices" that doesn't send `CTRL-EVENT-SCAN-STARTED`. (yay for ancient wpa_supplicant versions?)

Do you think it'd be reasonable to add a "quirk" here of "if wpa_supplicant didn't send `CTRL-EVENT-SCAN-STARTED` or "FAIL-BUSY*" as the first reply then assume it's old and cursed, so ignore `CTRL-EVENT-NETWORK-NOT-FOUND`?"

I'd be very happy to try and put something together and send a PR, but I don't have any devices to test with apart from two Auras...

### PR DESCRIPTION
**Pull request by projectgus**
This happens after the first set of results and the first CTRL-EVENT-NETWORK-NOT-FOUND if there are no preferred networks configured in wpa_supplicant - i.e. it considers the scan done and stops.

Closes #12.

Have implemented to call it on every iteration where nothing else happens because calling getStatus() seems more or less instant, and seems possible that some other versions may choose to go inactive at other times.

However, AFAIK if a preferred network is configured in wpa_supplicant then it won't go inactive - will keep scanning instead.

On my Kobo Aura the tested behaviour of `scanThenGetResults()` is:

* No Wi-Fi configured in Nickel - master branch takes 20 seconds to return, this PR takes 1-2 seconds (with same scan results).
* Wi-Fi configured in Nickel & connectable - connects in 1-2 seconds (no change with this PR).
* Wi-Fi configured in Nickel & not connectable - returns after 20 seconds with scan results (no change with this PR).

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/lj-wpaclient/13)

### CODE REVIEW

**Comment by NiLuJe** [comment]
The `INACTIVE` state seems pretty squarely designed for that "no enabled networks in the config" case, so that sounds good to me ;).

(c.f., https://w1.fi/wpa_supplicant/devel/defs_8h.html#a4aeb27c1e4abd046df3064ea9756f0bc).

Given that, I tried moving the status check to the closest related event, but it's not really any prettier, so, yeah, probably better this way.

```diff
diff --git a/wpaclient.lua b/wpaclient.lua
index 5582200..e852d97 100644
--- a/wpaclient.lua
+++ b/wpaclient.lua
@@ -220,8 +220,15 @@ function WpaClient.__index:scanThenGetResults()
             -- It may take *multiple* scans, and events may be split across multiple reads...
             -- Which is why NetworkManager does another pass of waiting in case our heuristics fail...
             elseif ev.msg == "CTRL-EVENT-NETWORK-NOT-FOUND" then
-                found_result = false
-                expected_scans = expected_scans + 1
+                local status
+                status, err = self:getStatus()
+                if status ~= nil and status.wpa_state ~= "INACTIVE" then
+                    -- If there are no enabled networks in the configuration, wpa_supplicant won't rescan,
+                    -- and switches to the INACTIVE state.
+                    -- c.f., https://w1.fi/wpa_supplicant/devel/defs_8h.html#a4aeb27c1e4abd046df3064ea9756f0bc
+                    found_result = false
+                    expected_scans = expected_scans + 1
+                end
 
             -- Wait for every started scan to finish
             -- NOTE: Because everything is terrible, this event isn't sent on older devices... -_-"
```

(Plus, we miiight want to re-use that check in the future anyway).

**Review by NiLuJe — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/koreader/lj-wpaclient/13)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @projectgus)

**Comment by projectgus** [comment]
> Given that, I tried moving the status check to the closest related event (i.e., the final one), but it's not really any prettier, so, yeah, probably better this way.

Yeah, I actually started out with it in a similar place but thought it was a little cleaner at the bottom of the loop! I also figured that I didn't know 100% what sequence of events every wpa_supplicant version might produce, so adding the check on every loop means it'll always catch it if it goes INACTIVE regardless of what event(s) come first.

> (Plus, we miiight want to re-use that check in the future anyway).

:smile:

**Comment by NiLuJe** [comment]
Thanks!

**Pull request merged**
